### ISSUE TITLE
Add windows 10 support

### ISSUE THREAD

**Issue by G0rocks** [theunixer/rlight#1]
Hi my name is Huldar and I've been looking for something like this in a while and I haven't found anything that is helpful. Can we perhaps add the funcionality for this software to run on windows? Thank you :)

**Comment by theunixer** [comment]
Hello. I really appreciate your interest in this project. I have already installed Windows on one of my machines. This weekend, I will try to add Windows support.

**Comment by theunixer** [comment]
_a quick note_

These are the libraries that could be used:
- cross-platform brightness monitoring & control: **brightness** crate.
- cross-platform access to camera:  **nokhwa** crate.
